trigger:
 - main
 - feature/*

name: recreate resource


stages: 
 - stage: build
   displayName: build
   pool: ajant-ka-jhund 
   jobs:
     - job: job1
       displayName: terraform install
       steps:
       
       - task: TerraformInstaller@1
         displayName: terraform install
         inputs:
           terraformVersion: 'latest'
       - task: TerraformTask@5
         displayName: terraform init
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: 'C:\STL_DATA\DevOps_Insider\vsts-agent-win-x64-4.269.0\_work\2\s\parent_mpdule'
           backendServiceArm: 'ajant ka jhund'
           backendAzureRmResourceGroupName: 'rg_infra1'
           backendAzureRmStorageAccountName: 'storageinfra12'
           backendAzureRmContainerName: 'contenerinfra1'
           backendAzureRmKey: 'terraform.tfstate'
      
       - task: TerraformTask@5
         displayName: terraform plan
         inputs:
           provider: 'azurerm'
           command: 'plan'
           workingDirectory: 'C:\STL_DATA\DevOps_Insider\vsts-agent-win-x64-4.269.0\_work\2\s\parent_mpdule'
           environmentServiceNameAzureRM: 'ajant ka jhund'


 - stage: scaning
   dependsOn: build
   displayName: scaning
   pool: ajant-ka-jhund
   jobs:
     - job:
       displayName: tfsec 
       steps:
       - task: tfsec@1
         inputs:
           version: 'v1.26.0'
       
 - stage: deploy
   dependsOn: scaning
   displayName: deploy
   pool: ajant-ka-jhund 
   jobs:
     - job: 
       displayName: terraform apply
       steps:
       - task: TerraformTask@5
         displayName: terraform init
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: 'C:\STL_DATA\DevOps_Insider\vsts-agent-win-x64-4.269.0\_work\2\s\parent_mpdule'
           backendAzureRmResourceGroupName: 'rg_infra1'
           backendAzureRmStorageAccountName: 'storageinfra12'
           backendAzureRmContainerName: 'contenerinfra1'
           backendAzureRmKey: 'terraform.tfstate'
       - task: TerraformTask@5
         displayName: terraform apply
         inputs:
           provider: 'azurerm'
           command: 'apply'
           workingDirectory: 'C:\STL_DATA\DevOps_Insider\vsts-agent-win-x64-4.269.0\_work\2\s\parent_mpdule'
           commandOptions: '-auto-approve'
           environmentServiceNameAzureRM: 'ajant ka jhund'
       


       
       


  
  
  
 




